spring:
  application:
    name: cloud-feign-hystrix-consumer
server:
  port: 8764
eureka:
  client:
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/   #本地的eruka服务地址
feign:
  hystrix:
    #开启feign的hystrix支持,默认是false
    enabled: true