#以下设置十分重要,在项目中都要设置,尤其涉及到文件上传的时候
hystrix.command.default.execution.timeout.enabled: false
#设置hystrix的默认超时时间为5分钟
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 300000
ribbon:
  #设置ribbon的连接超时时间为1分钟
  ConnectTimeout: 60000
  #ribbon的读取超时时间2分钟
  ReadTimeout: 120000